modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

issueTrackerURL="https://github.com/skiprocks999/Dynamic-Electricity/issues" #optional

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

displayURL="https://github.com/skiprocks999/Dynamic-Electricity" #optional

logoFile="dynamicelectricity.png" #optional

credits="Thanks to all contributors. Thanks to goshante with JEI fluid help." #optional

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[dependencies.dynamicelectricity]]
modId="electrodynamics"
mandatory=true
versionRange="[0.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.dynamicelectricity]]
modId="voltaic"
mandatory=true
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"